---
title: "Introduction to SpatialTouchstone"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to SpatialTouchstone}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r setup}
library(SpatiaTouchstone)
```

## Read Data 

Here, I am using An Xenium data as an example, using `readSpatial` function. 

```{r read data }
# Do not return a seurat object 
result <- readSpatial(sample_id = "test1",path="/mnt/scratch1/Touchstone_data/new_data/TOUCHSTONE_EAP_XRS_FFPE_PR_3_UOA_C_R1/",platform = "Xenium",seurat = FALSE)
print(result)
```

It can return a `Seurat` Object by seting the `seurat=TRUE`.

```{r read data as a seurat object }
# Return a seurat object 
result_seu <- readSpatial(sample_id = "test1",path="/mnt/scratch1/Touchstone_data/new_data/TOUCHSTONE_EAP_XRS_FFPE_PR_3_UOA_C_R1/",platform = "Xenium",seurat = TRUE)
print(result_seu)
```
## QC 

We have mutliple QC functions, when using seurat object as the input, it will return a dataframe which can be used to generate plot using our plot functions.


```{r getTxPerCell}
getTxPerCell_seu<- getTxPerCell(expMat="/mnt/scratch1/Touchstone_data/new_data/TOUCHSTONE_EAP_XRS_FFPE_PR_3_UOA_C_R1/cell_feature_matrix/",platform = "Xenium",seu_obj = result_seu)
getTxPerCell_seu
```

```{r getTxPerArea}
getTxPerArea_test_seu <- getTxPerArea(platform = "Xenium",seu_obj = result_seu)
getTxPerArea_test_seu
```

